# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Temas
                                 A QGIS plugin
 Gerenciar camadas dos temas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-28
        git sha              : $Format:%H$
        copyright            : (C) 2024 by nicolas jatobá
        email                : nwjs.ambiental@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.core import QgsProject, QgsMapThemeCollection, QgsExpressionContextUtils
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .temas_dockwidget import TemasDockWidget
import os.path


class Temas:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.project = QgsProject.instance()


        self.root = self.project.layerTreeRoot()
        self.model = self.iface.layerTreeView().layerTreeModel()



        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Temas_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Temas')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'Temas')
        self.toolbar.setObjectName(u'Temas')

        #print "** INITIALIZING Temas"

        self.pluginIsActive = False
        self.dockwidget = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Temas', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/temas/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Temas'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING Temas"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD Temas"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Temas'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------
    def populate_layouts(self):
        self.dockwidget.LayoutComboBox.clear()
        mlt = self.project.layoutManager()
        layouts = mlt.layouts()
        layouts_names = [layout.name() for layout in layouts]
        self.dockwidget.LayoutComboBox.addItems(layouts_names)

    def change_layout(self, new_value):
        QgsExpressionContextUtils.setProjectVariable(
            self.project, 'layout', new_value)
        print(new_value)

    def onChangeLayout(self):
        self.dockwidget.LayoutComboBox.currentTextChanged.connect(
            self.change_layout)
        
    def populate_themes(self):
        self.dockwidget.ThemeComboBox.clear()
        mtc = self.project.mapThemeCollection()
        themes = mtc.mapThemes()
        self.dockwidget.ThemeComboBox.addItems(themes)
        self.set_combo_theme()

    def set_combo_theme(self):
        theme = self.get_current_theme()
        if theme != None:
            index = self.dockwidget.ThemeComboBox.findText(theme, Qt.MatchFixedString)
            self.dockwidget.ThemeComboBox.setCurrentIndex(index)
    
    def theme_changed(self):
        theme = self.dockwidget.ThemeComboBox.currentText()
        self.project.mapThemeCollection().applyTheme(theme, self.root, self.model)

    def replace_theme(self):
        theme = self.dockwidget.ThemeComboBox.currentText()
        rec = self.project.mapThemeCollection().createThemeFromCurrentState(self.root, self.model)
        self.project.mapThemeCollection().update(theme, rec)

    def include_union_municipal_layer_on_context_themes(self):
        layer_to_add_name = 'municipio - empreendimento'
        mtc = self.project.mapThemeCollection()
        themes = mtc.mapThemes()
        for theme in themes:
            if 'CONTEXTO' in theme:
                theme_state = mtc.mapThemeState(theme)
                layer_to_add = self.project.mapLayersByName(layer_to_add_name)[0]
                layer_record = QgsMapThemeCollection.MapThemeLayerRecord(layer_to_add)
                theme_state.addLayerRecord(layer_record)
                mtc.update(theme, theme_state)

    def get_current_theme(self):
        mtc = self.project.mapThemeCollection()
        themes = mtc.mapThemes()

        root = self.project.layerTreeRoot()
        model = self.iface.layerTreeView().layerTreeModel()

        currentTheme = mtc.createThemeFromCurrentState(root, model)
        for theme in themes:
            if mtc.mapThemeState(theme) == currentTheme:
                print('mapThemes: ', mtc.mapThemes())
                return theme

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING Temas"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = TemasDockWidget()

            self.populate_layouts()

            self.populate_themes()
           
            self.onChangeLayout()

            self.dockwidget.ThemeComboBox.currentIndexChanged.connect(
                self.theme_changed)

            self.dockwidget.ReplaceThemeButton.clicked.connect(
                self.replace_theme)

            self.dockwidget.IncludeContextButton.clicked.connect(
                self.include_union_municipal_layer_on_context_themes)

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
